In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [8]:
df = pd.read_excel("new_home_data.xlsx")
df

Area  bedrooms  age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000

#### Exercise notes
In multivaiable regression multiple independent variables will be used to find out the dependent variable

so math looks somehting like this 

**price = m1 * area + m2 * bedrooms + m3 * age + b**  or (y=m1x1+m2x2+m3x3 +b)

*price - Dependent variable*

*area,bedrooms,age = Independent variables(features)*

*b - Intercepter*

*m1,m2,m3 = Is the coefficents*


## Topics 

1. Data Preprocessing: Handling NA Values
2. Linear Regression Using Multiple Variables

In [9]:
df.bedrooms.median()

3.5

In [11]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [12]:
df.bedrooms.fillna(3)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [13]:
df.bedrooms =df.bedrooms.fillna(3)
df

Area  bedrooms  age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  680000
4  4000       5.0    8  725000

In [14]:
reg = linear_model.LinearRegression()

In [17]:
reg.fit(df[["Area","bedrooms","age"]],df.Price)

LinearRegression()

In [19]:
reg.predict([[3000,3,40]])

C:\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([597200.])

In [20]:
reg.predict([[2500,4,5]])

C:\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([506812.5])

In [21]:
reg.coef_

array([  143.625, -6762.5  ,   337.5  ])

In [22]:
reg.intercept_

173112.50000000012

In [23]:
143.625*2500+-6762.5 *4+337.5 *5 +173112.50000000012

506812.5000000001

In [26]:
predict_price = pd.DataFrame({
    'Area' : [3500,2500,5000,1200,1700],
    'bedrooms':[4,3,6,2,3],
    'age':[15,10,2,20,9]
})
predict_price

Area  bedrooms  age
0  3500         4   15
1  2500         3   10
2  5000         6    2
3  1200         2   20
4  1700         3    9

In [30]:
p= reg.predict(predict_price)

In [31]:
predict_price["Price"]=p

In [32]:
predict_price

Area  bedrooms  age     Price
0  3500         4   15  653812.5
1  2500         3   10  515262.5
2  5000         6    2  851337.5
3  1200         2   20  338687.5
4  1700         3    9  400025.0

In [33]:
predict_price.to_csv("new_predictPrice.csv",index=False)