In [37]:
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()
from sklearn import svm
import numpy as np

In [10]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [11]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["target"]=iris.target
df["flower"]=df["target"].apply(lambda x : iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  flower  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [12]:
x=iris.data
y=iris.target

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [26]:
model=svm.SVC(kernel="rbf",C=30,gamma="auto")
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9777777777777777

### stratified KFlod using cross_val_score function

In [27]:
from sklearn.model_selection import cross_val_score

In [30]:
svm_score=cross_val_score(model,iris.data,iris.target,cv=3)

In [31]:
svm_score

array([0.98, 0.94, 0.96])

In [32]:
svm_score=cross_val_score(svm.SVC(kernel="linear",C=10,gamma="auto"),iris.data,iris.target,cv=3)
svm_score

array([1.  , 0.94, 0.98])

In [33]:
svm_score=cross_val_score(svm.SVC(kernel="linear",C=20,gamma="auto"),iris.data,iris.target,cv=3)
svm_score

array([1.  , 0.94, 0.96])

### instead of repeating we could have used the for loop like below

In [38]:
kernels = ["rbf","linear"]
C= [1,10,20]
avg_scores={}
for kval in kernels:
    for cval in C:
        cv_scores=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma="auto"),iris.data,iris.target,cv=5)
        avg_scores[kval+"_"+str(cval)]=np.average(cv_scores)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

### Other better way is called grid search

In [39]:
from sklearn.model_selection import GridSearchCV

clf=GridSearchCV(svm.SVC(gamma="auto"),{
    "C":[1,10,20],
    "kernel":["rbf","linear"]
},cv=5,return_train_score=False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00149207, 0.00058436, 0.00240788, 0.00099607, 0.00100412,
        0.00061955]),
 'std_fit_time': array([0.00056591, 0.0007357 , 0.00135066, 0.00064864, 0.00026849,
        0.00046718]),
 'mean_score_time': array([0.0011291 , 0.00073891, 0.00059485, 0.0014564 , 0.00011363,
        0.00019984]),
 'std_score_time': array([0.0014336 , 0.00042483, 0.00048579, 0.00055543, 0.00022726,
        0.00039968]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [40]:
n_df=pd.DataFrame(clf.cv_results_)
n_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001492      0.000566         0.001129        0.001434       1   
1       0.000584      0.000736         0.000739        0.000425       1   
2       0.002408      0.001351         0.000595        0.000486      10   
3       0.000996      0.000649         0.001456        0.000555      10   
4       0.001004      0.000268         0.000114        0.000227      20   
5       0.000620      0.000467         0.000200        0.000400      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [41]:
n_df[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [42]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_

In [43]:
clf.best_score_

0.9800000000000001

In [44]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

### to help with the computing problem with a larger datasets we can use the RandomizedSearchCV mehtond

In [46]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(svm.SVC(gamma="auto"),{
    "C":[1,10,20],
    "kernel":["rbf","linear"]
},cv=5,return_train_score=False,n_iter=2)
rs.fit(iris.data,iris.target)
pd.DataFrame(rs.cv_results_)[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0       1          rbf             0.98
1      10          rbf             0.98

### Now How to choose to best model for your project

In [47]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [52]:
model_params={
    "svm":{
        "model":svm.SVC(gamma="auto"),
        "params":{
            "C":[1,10,20],
            "kernel":["rbf","linear"]
        }
    },
    "random_forest":{
        "model":RandomForestClassifier(),
        "params":{
            "n_estimators":[1,5,10]
        }
    },
    "logistic_regression":{
        "model":LogisticRegression(solver="liblinear",multi_class="auto"),
        "params":{
            "C":[1,5,10]
        }
    }
}

In [54]:
scores=[]

for model_name,mp in model_params.items():
    clf=GridSearchCV(mp["model"],mp["params"],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        "model":model_name,
        "best_score":clf.best_score_,
        "best_params":clf.best_params_
    })

In [55]:
scores

[{'model': 'svm',
  'best_score': 0.9800000000000001,
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': 0.9466666666666667,
  'best_params': {'n_estimators': 1}},
 {'model': 'logistic_regression',
  'best_score': 0.9666666666666668,
  'best_params': {'C': 5}}]

In [57]:
nn_df=pd.DataFrame(scores,columns=["model","best_score","best_params"])
nn_df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.946667        {'n_estimators': 1}
2  logistic_regression    0.966667                   {'C': 5}