In [22]:
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()
from sklearn.linear_model import LogisticRegression
Log =LogisticRegression(max_iter=3000)
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=40)
from sklearn.svm import SVC
svm= SVC()
import numpy as np

In [13]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [14]:
from sklearn.model_selection import cross_val_score

In [24]:
log_score=cross_val_score(Log,iris.data,iris.target,cv=3)
log_score

array([0.98, 0.96, 0.98])

In [25]:
np.average(log_score)

0.9733333333333333

In [26]:
rf_score =cross_val_score(rf,iris.data,iris.target,cv=3)
rf_score

array([0.98, 0.92, 0.98])

In [27]:
np.average(rf_score)

0.96

In [28]:
svm_score=cross_val_score(svm,iris.data,iris.target,cv=3)
svm_score

array([0.96, 0.98, 0.94])

In [29]:
np.average(svm_score)

0.96